Upstream: no
Reason: bug on big-endian systems
Url: https://github.com/libgit2/pygit2/issues/812
diff --git a/test/test_patch.py b/test/test_patch.py
index ae5c34f..f3981c4 100644
--- a/test/test_patch.py
+++ b/test/test_patch.py
@@ -25,6 +25,7 @@

 import pygit2
 import pytest
+import platform


 BLOB_OLD_SHA = 'a520c24d85fbfc815d385957eed41406ca5a860b'
@@ -161,6 +162,7 @@ def test_context_lines(testrepo):

     assert context_count != 0

+@pytest.mark.xfail(platform.machine() == 's390x', reason='bug')
 def test_no_context_lines(testrepo):
     old_blob = testrepo[BLOB_OLD_SHA]
     new_blob = testrepo[BLOB_NEW_SHA]

